# Generated by Django 5.0.2 on 2024-03-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
