# Generated by Django 5.0.2 on 2024-03-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_remove_uploadedfile_file_uploadedfile_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
