# Generated by Django 5.0.2 on 2024-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_uploadedfile_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
