# Generated by Django 5.0.2 on 2024-03-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
